export type {
  Acl,
  AddPartitions,
  BrokerRow,
  CleanupPolicy,
  ClientQuota,
  ClusterHealth,
  ConfigEntry,
  CreateAcls,
  CreateTopic,
  EditSubject,
  EditTopicConfigs,
  GroupDetail,
  GroupMember,
  GroupOffset,
  GroupRow,
  GroupState,
  Identity,
  LaneHealth,
  LogDir,
  OffsetMove,
  PartitionRow,
  PayloadEncoding,
  PrivilegeName,
  ProduceRecord,
  ProducedRecord,
  QuotaEntity,
  QuotaEntityType,
  Record as KafkaRecord,
  RecordOrder,
  RegisterSchema,
  RegisteredVersion,
  ResetOffsets,
  ResetTarget,
  SchemaCompatibility,
  SchemaReference,
  SchemaType,
  SubjectDetail,
  SubjectRow,
  TopicDetail,
  TopicGroupRow,
  TopicRow,
} from "@/api/types.gen";

import type { SearchHit as SearchHitWire } from "@/api/types.gen";

export type SearchHit = SearchHitWire & {
  href: string;
};
