[workspace]
resolver = "3"
members = [
    "crates/klens",
    "crates/klens-app",
    "crates/klens-server",
    "crates/klens-telemetry",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false

[workspace.dependencies]
klens-app = { path = "crates/klens-app" }
klens-server = { path = "crates/klens-server" }
klens-telemetry = { path = "crates/klens-telemetry" }

tokio = { version = "1", features = ["full"] }
axum = { version = "0.8", features = ["http2"] }
tower = { version = "0.5.3" }
tower-http = { version = "0.6", features = ["catch-panic", "trace", "request-id", "sensitive-headers"] }
clap = { version = "4", features = ["derive", "env"] }
anyhow = "1"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
