[package]
name = "klens"
version = "0.1.0"
edition = "2024"
publish = false

[features]
ui = ["dep:rust-embed", "dep:mime_guess"]

[workspace]
members = ["xtask"]
default-members = ["."]

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
all = "deny"

[dependencies]
anyhow = "1"
async-trait = "0.1"
indexmap = "2"
axum = { version = "0.8", features = ["http2", "ws"] }
axum-extra = { version = "0.12.6", features = ["cookie-private"] }
cookie = { version = "0.18.2", features = ["key-expansion", "private"] }
futures = "0.3"
juniper = { version = "0.17", features = ["schema-language"] }
juniper_axum = { version = "0.3", features = ["subscriptions"] }
juniper_graphql_ws = { version = "0.5", features = ["graphql-transport-ws", "graphql-ws"] }
moka = { version = "0.12", features = ["future"] }
mime_guess = { version = "2", optional = true }
openidconnect = "4.0.1"
rdkafka = { version = "0.39", features = ["ssl-vendored", "libz-static"] }
rust-embed = { version = "8", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml_ng = "0.10"
shellexpand = { version = "3.1", default-features = false, features = ["base-0"] }
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.5.3", features = ["util"] }
tower-http = { version = "0.6", features = ["catch-panic", "trace", "request-id", "sensitive-headers"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5.8"
base64 = "0.22"
progenitor-client = "0.14"
reqwest = { version = "0.13", default-features = false, features = ["json", "query", "rustls"] }

[build-dependencies]
openapiv3 = "2"
prettyplease = "0.2"
progenitor = "0.14"
serde_json = "1"
serde_path_to_error = "0.1"
serde_yaml_ng = "0.10"
syn = "2"

[dev-dependencies]
juniper_subscriptions = "0.18"
tokio = { version = "1", features = ["test-util"] }
wiremock = "0.6.5"

[profile.release]
opt-level = 3
strip = true
lto = "thin"
panic = 'abort'
codegen-units = 1
