[package]
name = "klens"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = ["ui"]
ui = ["klens-server/ui"]

[dependencies]
klens-app.workspace = true
klens-server = { workspace = true, default-features = false }
klens-telemetry.workspace = true

anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
