// Generated by `cargo xtask types`. Do not edit.

export type PrivilegeName = "RECORDS" | "CONFIGS" | "SCHEMA_TEXT" | "ACLS";

export type ClusterGrant = { cluster: string, 
/**
 * Names of the roles that granted this access, for tracing a privilege
 * back to an IdP group mapping. Empty when no role table applies.
 */
roles: Array<string>, privileges: Array<PrivilegeName>, 
/**
 * False when the cluster refuses every change, whatever the privileges.
 */
writable: boolean, };

export type Identity = { 
/**
 * `null` when authentication is disabled.
 */
subject: string | null, clusters: Array<ClusterGrant>, };

export type LaneHealth = { updatedAt: string | null, checkedAt: string | null, lastError: string | null, lastPollMs: number | null, 
/**
 * False once a lane has failed since its last successful commit.
 */
healthy: boolean, };

export type ClusterHealth = { cluster: string, ready: boolean, topology: LaneHealth, watermarks: LaneHealth, offsets: LaneHealth, configs: LaneHealth, subjects: LaneHealth, logDirs: LaneHealth, acls: LaneHealth, quotas: LaneHealth, topicCount: number, partitionCount: number, groupCount: number, brokerCount: number, subjectCount: number, underReplicatedPartitions: number, offlinePartitions: number, };

export type CleanupPolicy = "DELETE" | "COMPACT" | "COMPACT_DELETE";

export type TopicRow = { name: string, internal: boolean, partitionCount: number, replicationFactor: number, 
/**
 * Messages currently in the log (`Σ high − low`).
 */
retainedMessages: number, 
/**
 * Messages ever produced (`Σ high`). Overstates a retention-truncated
 * topic, so it is not the display default.
 */
producedTotal: number, 
/**
 * Bytes in one replica of each partition, the largest. Null until a log
 * dirs poll reports the topic.
 */
sizeBytes: number | null, rate: number, 
/**
 * Null until the topic's configs report a `retention.ms` value.
 */
retentionMs: number | null, cleanupPolicy: CleanupPolicy, groupCount: number, underReplicated: boolean, };

export type PartitionRow = { id: number, leader: number, replicas: Array<number>, isr: Array<number>, lowWatermark: number, highWatermark: number, retained: number, underReplicated: boolean, 
/**
 * Bytes in the largest replica. Null until a log dirs poll reports the
 * partition.
 */
sizeBytes: number | null, };

export type TopicDetail = { name: string, internal: boolean, partitions: Array<PartitionRow>, replicationFactor: number, retainedMessages: number, producedTotal: number, 
/**
 * Bytes in one replica of each partition, the largest. Null until a log
 * dirs poll reports the topic.
 */
sizeBytes: number | null, 
/**
 * Bytes in every replica of every partition.
 */
diskBytes: number | null, rate: number, 
/**
 * Null until the topic's configs report a `retention.ms` value.
 */
retentionMs: number | null, cleanupPolicy: CleanupPolicy, groupCount: number, underReplicated: boolean, };

export type GroupState = "STABLE" | "EMPTY" | "PREPARING_REBALANCE" | "COMPLETING_REBALANCE" | "DEAD";

export type MemberAssignment = { topic: string, partitions: Array<number>, };

export type GroupMember = { id: string, clientId: string, host: string, assignments: Array<MemberAssignment>, };

export type GroupOffset = { topic: string, partition: number, currentOffset: number | null, endOffset: number | null, lag: number | null, memberId: string | null, };

export type GroupRow = { id: string, state: GroupState, memberCount: number, topicNames: Array<string>, 
/**
 * Null until the group's committed offsets are first fetched.
 */
totalLag: number | null, 
/**
 * False when a committed partition had no watermark to join against, so
 * the total understates the real lag.
 */
lagComplete: boolean, };

export type GroupDetail = { id: string, state: GroupState, protocol: string, members: Array<GroupMember>, offsets: Array<GroupOffset>, totalLag: number | null, lagComplete: boolean, };

export type TopicGroupRow = { id: string, state: GroupState, memberCount: number, lagOnTopic: number | null, };

export type LogDir = { path: string, 
/**
 * Set when the directory is offline, as a Kafka error name.
 */
error: string | null, 
/**
 * Size of the volume the directory lives on. Null for brokers before
 * Kafka 3.3.
 */
totalBytes: number | null, usableBytes: number | null, 
/**
 * A cordoned directory takes no new partitions.
 */
cordoned: boolean, 
/**
 * Every log in the directory, including a replica still moving in.
 */
sizeBytes: number, replicaCount: number, };

export type BrokerRow = { id: number, host: string, port: number, rack: string | null, controller: boolean, partitionCount: number, leaderCount: number, 
/**
 * Bytes in this broker's log dirs. Null until a log dirs poll reports
 * the broker.
 */
sizeBytes: number | null, 
/**
 * Sorted by path.
 */
logDirs: Array<LogDir>, };

export type ConfigSource = "DYNAMIC_TOPIC_CONFIG" | "DYNAMIC_BROKER_CONFIG" | "STATIC_BROKER_CONFIG" | "DEFAULT_CONFIG";

export type ConfigEntry = { name: string, value: string | null, source: ConfigSource, readOnly: boolean, sensitive: boolean, };

export type SchemaType = "AVRO" | "JSON" | "PROTOBUF";

export type SchemaCompatibility = "BACKWARD" | "FORWARD" | "FULL" | "NONE";

export type SubjectRow = { subject: string, id: number, type: SchemaType, latestVersion: number, versions: Array<number>, compatibility: SchemaCompatibility, };

export type SubjectRowsResult = { rows: Array<SubjectRow>, sourceHealth: LaneHealth, };

export type SchemaReference = { name: string, subject: string, version: number, };

export type SubjectDetail = { subject: string, version: number, id: number, type: SchemaType, schema: string, references: Array<SchemaReference>, };

export type AclStatus = "PENDING" | "ENABLED" | "DISABLED" | "DENIED";

export type AclResourceType = "TOPIC" | "GROUP" | "CLUSTER" | "TRANSACTIONAL_ID" | "DELEGATION_TOKEN";

export type AclPatternType = "LITERAL" | "PREFIXED";

export type AclOperation = "ALL" | "READ" | "WRITE" | "CREATE" | "DELETE" | "ALTER" | "DESCRIBE" | "CLUSTER_ACTION" | "DESCRIBE_CONFIGS" | "ALTER_CONFIGS" | "IDEMPOTENT_WRITE";

export type AclPermission = "ALLOW" | "DENY";

export type Acl = { resourceType: AclResourceType, resourceName: string, patternType: AclPatternType, principal: string, host: string, operation: AclOperation, permission: AclPermission, };

export type AclListing = { status: AclStatus, bindings: Array<Acl>, sourceHealth: LaneHealth, };

export type QuotaStatus = "PENDING" | "DESCRIBED" | "DENIED";

export type QuotaEntityType = "USER" | "CLIENT_ID" | "IP";

export type QuotaEntity = { entityType: QuotaEntityType, name: string | null, };

export type ClientQuota = { entity: Array<QuotaEntity>, producerByteRate: number | null, consumerByteRate: number | null, requestPercentage: number | null, controllerMutationRate: number | null, connectionCreationRate: number | null, };

export type QuotaListing = { status: QuotaStatus, quotas: Array<ClientQuota>, sourceHealth: LaneHealth, };

export type RecordOrder = "NEWEST" | "OLDEST";

export type RecordHeader = { key: string, value: string, };

export type Record = { topic: string, partition: number, offset: number, timestamp: string, key: string | null, value: string | null, schemaId: number | null, headers: Array<RecordHeader>, sizeBytes: number, };

export type RecordPage = { records: Array<Record>, 
/**
 * False when the scan hit its deadline with windows still unread: the
 * records are real, but the page is not everything the query matched.
 * `nextCursor` resumes where the scan stopped.
 */
complete: boolean, 
/**
 * True when an obfuscation rule covers this topic. Keys, values, and
 * headers are then a view of the records: protected fields render as
 * `***` or as `kx:` tokens, a value that never decoded may be masked
 * whole, and filters match that view rather than the wire record.
 */
obfuscated: boolean, nextCursor: string | null, prevCursor: string | null, };

export type RecordLookup = { record: Record, obfuscated: boolean, };

export type TailStart = { partition: number, offset: number, };

export type TailEvent = { "type": "ready", start: Array<TailStart>, obfuscated: boolean, } | { "type": "records", records: Array<Record>, skipped: number, };

export type SearchKind = "TOPIC" | "GROUP" | "NODE" | "SUBJECT";

export type SearchHit = { kind: SearchKind, id: string, label: string, detail: string, };

export type TopicRate = { topic: string, rate: number, };

export type Update = { "type": "watermarks", 
/**
 * One `{topic, rate}` pair per topic, never catalog objects. A scoped
 * subscriber gets only its topic.
 */
topics: Array<TopicRate>, } | { "type": "groupLag", group: string, lag: number, lagComplete: boolean, offsets: Array<GroupOffset>, } | { "type": "topology", addedTopics: Array<string>, removedTopics: Array<string>, changedTopics: Array<string>, addedGroups: Array<string>, removedGroups: Array<string>, changedGroups: Array<string>, brokersChanged: boolean, } | { "type": "configs", topics: Array<string>, } | { "type": "subjects", removed: Array<string>, changed: Array<string>, } | { "type": "logDirs", topics: Array<string>, brokersChanged: boolean, } | { "type": "acls" } | { "type": "quotas" } | { "type": "resync" };

