// Generated by `cargo xtask types`. Do not edit.

export type Int64 = string;

export type PrivilegeName = "RECORDS" | "CONFIGS" | "SCHEMA_TEXT" | "ACLS" | "RESET_OFFSETS" | "DELETE_GROUP_OFFSETS";

export type ClusterGrant = { cluster: string, 
/**
 * Names of the roles that granted this access, for tracing a privilege
 * back to an IdP group mapping. Empty when no role table applies.
 */
roles: Array<string>, privileges: Array<PrivilegeName>, };

export type Identity = { 
/**
 * `null` when authentication is disabled.
 */
subject: string | null, clusters: Array<ClusterGrant>, };

export type LaneHealth = { updatedAt: string | null, checkedAt: string | null, lastError: string | null, lastPollMs: Int64 | null, 
/**
 * False once a lane has failed since its last successful commit.
 */
healthy: boolean, };

export type ClusterHealth = { cluster: string, ready: boolean, topology: LaneHealth, watermarks: LaneHealth, offsets: LaneHealth, configs: LaneHealth, subjects: LaneHealth, topicCount: number, partitionCount: number, groupCount: number, brokerCount: number, subjectCount: number, underReplicatedPartitions: number, offlinePartitions: number, };

export type CleanupPolicy = "DELETE" | "COMPACT" | "COMPACT_DELETE";

export type TopicRow = { name: string, internal: boolean, partitionCount: number, replicationFactor: number, 
/**
 * Messages currently in the log (`Σ high − low`).
 */
retainedMessages: Int64, 
/**
 * Messages ever produced (`Σ high`). Overstates a retention-truncated
 * topic, so it is not the display default.
 */
producedTotal: Int64, rate: number, 
/**
 * Null until the topic's configs report a `retention.ms` value.
 */
retentionMs: Int64 | null, cleanupPolicy: CleanupPolicy, groupCount: number, underReplicated: boolean, };

export type TopicRowPage = { rows: Array<TopicRow>, 
/**
 * Rows matching the filter before paging, so a client can size its
 * scrollbar without walking every page.
 */
total: number, nextCursor: string | null, };

export type PartitionRow = { id: number, leader: number, replicas: Array<number>, isr: Array<number>, lowWatermark: Int64, highWatermark: Int64, retained: Int64, underReplicated: boolean, };

export type TopicDetail = { name: string, internal: boolean, partitions: Array<PartitionRow>, replicationFactor: number, retainedMessages: Int64, producedTotal: Int64, rate: number, 
/**
 * Null until the topic's configs report a `retention.ms` value.
 */
retentionMs: Int64 | null, cleanupPolicy: CleanupPolicy, groupCount: number, underReplicated: boolean, };

export type GroupState = "STABLE" | "EMPTY" | "PREPARING_REBALANCE" | "COMPLETING_REBALANCE" | "DEAD";

export type MemberAssignment = { topic: string, partitions: Array<number>, };

export type GroupMember = { id: string, clientId: string, host: string, assignments: Array<MemberAssignment>, };

export type GroupOffset = { topic: string, partition: number, currentOffset: Int64 | null, endOffset: Int64 | null, lag: Int64 | null, memberId: string | null, };

export type GroupRow = { id: string, state: GroupState, memberCount: number, topicNames: Array<string>, 
/**
 * Null until the group's committed offsets are first fetched.
 */
totalLag: Int64 | null, 
/**
 * False when a committed partition had no watermark to join against, so
 * the total understates the real lag.
 */
lagComplete: boolean, coordinatorId: number, };

export type GroupRowPage = { rows: Array<GroupRow>, total: number, nextCursor: string | null, };

export type GroupDetail = { id: string, state: GroupState, protocol: string, coordinatorId: number, members: Array<GroupMember>, offsets: Array<GroupOffset>, totalLag: Int64 | null, lagComplete: boolean, };

export type ResetTo = { "kind": "earliest" } | { "kind": "latest" } | { "kind": "timestamp", timestamp: Int64, } | { "kind": "offset", offset: Int64, } | { "kind": "shift", by: Int64, };

export type ResetOffsetsRequest = { group: string, topic?: string, partitions?: Array<number>, to: ResetTo, dryRun: boolean, };

export type OffsetChange = { topic: string, partition: number, current: Int64 | null, target: Int64, };

export type OffsetReset = { group: string, applied: boolean, partitions: Array<OffsetChange>, };

export type DeleteOffsetsRequest = { group: string, topic: string, partitions?: Array<number>, confirm: string, };

export type DeletedOffsets = { group: string, topic: string, partitions: Array<number>, };

export type TopicGroupRow = { id: string, state: GroupState, memberCount: number, lagOnTopic: Int64 | null, };

export type BrokerRow = { id: number, host: string, port: number, rack: string | null, controller: boolean, partitionCount: number, leaderCount: number, };

export type ConfigSource = "DYNAMIC_TOPIC_CONFIG" | "DYNAMIC_BROKER_CONFIG" | "STATIC_BROKER_CONFIG" | "DEFAULT_CONFIG";

export type ConfigEntry = { name: string, value: string | null, source: ConfigSource, readOnly: boolean, sensitive: boolean, };

export type SchemaType = "AVRO" | "JSON" | "PROTOBUF";

export type SchemaCompatibility = "BACKWARD" | "FORWARD" | "FULL" | "NONE";

export type SubjectRow = { subject: string, id: number, type: SchemaType, latestVersion: number, versions: Array<number>, compatibility: SchemaCompatibility, };

export type SubjectRowsResult = { rows: Array<SubjectRow>, sourceHealth: LaneHealth, };

export type SchemaReference = { name: string, subject: string, version: number, };

export type SubjectDetail = { subject: string, version: number, id: number, type: SchemaType, schema: string, references: Array<SchemaReference>, };

export type AclAuthorizer = "ENABLED" | "DISABLED";

export type AclResourceType = "TOPIC" | "GROUP" | "CLUSTER" | "TRANSACTIONAL_ID" | "DELEGATION_TOKEN";

export type AclPatternType = "LITERAL" | "PREFIXED";

export type AclOperation = "ALL" | "READ" | "WRITE" | "CREATE" | "DELETE" | "ALTER" | "DESCRIBE" | "CLUSTER_ACTION" | "DESCRIBE_CONFIGS" | "ALTER_CONFIGS" | "IDEMPOTENT_WRITE";

export type AclPermission = "ALLOW" | "DENY";

export type Acl = { resourceType: AclResourceType, resourceName: string, patternType: AclPatternType, principal: string, host: string, operation: AclOperation, permission: AclPermission, };

export type AclListing = { authorizer: AclAuthorizer, bindings: Array<Acl>, };

export type Compression = "NONE" | "GZIP" | "SNAPPY" | "LZ4" | "ZSTD";

export type RecordOrder = "NEWEST" | "OLDEST";

export type RecordHeader = { key: string, value: string, };

export type Record = { topic: string, partition: number, offset: Int64, timestamp: string, key: string | null, value: string | null, schemaId: number | null, headers: Array<RecordHeader>, sizeBytes: Int64, compression: Compression, };

export type RecordPage = { records: Array<Record>, 
/**
 * False when the scan hit its deadline with windows still unread: the
 * records are real, but the page is not everything the query matched.
 * `nextCursor` resumes where the scan stopped.
 */
complete: boolean, 
/**
 * True when an obfuscation rule covers this topic. Keys, values, and
 * headers are then a view of the records: protected fields render as
 * `***` or as `kx:` tokens, a value that never decoded may be masked
 * whole, and filters match that view rather than the wire record.
 */
obfuscated: boolean, nextCursor: string | null, prevCursor: string | null, };

export type TailStart = { partition: number, offset: Int64, };

export type TailEvent = { "type": "ready", start: Array<TailStart>, obfuscated: boolean, } | { "type": "records", records: Array<Record>, skipped: Int64, };

export type SearchKind = "TOPIC" | "GROUP" | "NODE" | "SUBJECT";

export type SearchHit = { kind: SearchKind, id: string, label: string, detail: string, };

export type TopicSortField = "NAME" | "RATE" | "RETAINED_MESSAGES" | "PARTITIONS" | "GROUPS";

export type TopicRate = { topic: string, rate: number, };

export type ResyncReason = "LAGGED";

export type Update = { "type": "watermarks", at: string, 
/**
 * One `{topic, rate}` pair per topic, never catalog objects. A scoped
 * subscriber gets only its topic.
 */
topics: Array<TopicRate>, } | { "type": "groupLag", at: string, group: string, lag: Int64, lagComplete: boolean, offsets: Array<GroupOffset>, } | { "type": "topology", version: Int64, addedTopics: Array<string>, removedTopics: Array<string>, changedTopics: Array<string>, addedGroups: Array<string>, removedGroups: Array<string>, changedGroups: Array<string>, brokersChanged: boolean, } | { "type": "configs", version: Int64, topics: Array<string>, } | { "type": "subjects", version: Int64, added: Array<string>, removed: Array<string>, changed: Array<string>, } | { "type": "resync", reason: ResyncReason, };

