use std::path::Path;

use ts_rs::TS;
use xshell::Shell;

use klens::app::typescript::{
    Acl, AclAuthorizer, AclListing, AclOperation, AclPatternType, AclPermission, AclResourceType,
    BrokerRow, CleanupPolicy, ClusterGrant, ClusterHealth, Compression, ConfigEntry, ConfigSource,
    GroupDetail, GroupMember, GroupOffset, GroupRow, GroupRowPage, GroupState, Identity, Int64,
    LaneHealth, MemberAssignment, PartitionRow, PrivilegeName, Record, RecordHeader, RecordOrder,
    RecordPage, ResyncReason, SchemaCompatibility, SchemaReference, SchemaType, SearchHit,
    SearchKind, SubjectDetail, SubjectRow, SubjectRowsResult, TailEvent, TailStart, TopicDetail,
    TopicGroupRow, TopicRate, TopicRow, TopicRowPage, TopicSortField, Update,
};

pub fn run(sh: &Shell) -> xshell::Result<()> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../web/src/api/types.gen.ts");
    sh.write_file(path, typescript())?;
    Ok(())
}

fn typescript() -> String {
    let cfg = ts_rs::Config::from_env();
    let mut out = String::from("// Generated by `cargo xtask types`. Do not edit.\n\n");
    macro_rules! emit {
        ($($ty:ty),+ $(,)?) => {
            $(
                out.push_str("export ");
                out.push_str(&<$ty as TS>::decl(&cfg));
                out.push_str("\n\n");
            )+
        };
    }
    emit!(
        Int64,
        PrivilegeName,
        ClusterGrant,
        Identity,
        LaneHealth,
        ClusterHealth,
        CleanupPolicy,
        TopicRow,
        TopicRowPage,
        PartitionRow,
        TopicDetail,
        GroupState,
        MemberAssignment,
        GroupMember,
        GroupOffset,
        GroupRow,
        GroupRowPage,
        GroupDetail,
        TopicGroupRow,
        BrokerRow,
        ConfigSource,
        ConfigEntry,
        SchemaType,
        SchemaCompatibility,
        SubjectRow,
        SubjectRowsResult,
        SchemaReference,
        SubjectDetail,
        AclAuthorizer,
        AclResourceType,
        AclPatternType,
        AclOperation,
        AclPermission,
        Acl,
        AclListing,
        Compression,
        RecordOrder,
        RecordHeader,
        Record,
        RecordPage,
        TailStart,
        TailEvent,
        SearchKind,
        SearchHit,
        TopicSortField,
        TopicRate,
        ResyncReason,
        Update,
    );
    out
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::typescript;

    #[test]
    fn generated_typescript_is_checked_in() {
        let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../web/src/api/types.gen.ts");
        let actual = std::fs::read_to_string(&path).unwrap_or_default();

        assert_eq!(
            actual,
            typescript(),
            "frontend types are stale; run `cargo xtask types`"
        );
    }
}
