[package]
name = "e2e"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
klens = { path = ".." }
krafka = { git = "https://github.com/hupe1980/krafka", rev = "e6b154cef8dd0bfe7b2c8fadbf925c1e6494310f" }
reqwest = { version = "0.12", default-features = false }
serde_json = "1"
tempfile = "3"
testcontainers-modules = { version = "0.15", features = ["kafka"] }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "time"] }
