use ts_rs::TS;

use super::acls::{
    Acl, AclAuthorizer, AclListing, AclOperation, AclPatternType, AclPermission, AclResourceType,
};
use super::brokers::BrokerRow;
use super::clusters::{ClusterHealth, LaneHealth};
use super::configs::{ConfigEntry, ConfigSource};
use super::groups::{
    GroupDetail, GroupMember, GroupOffset, GroupRow, GroupRowPage, GroupState, MemberAssignment,
};
use super::int64::Int64;
use super::records::{Compression, Record, RecordHeader, RecordOrder, RecordPage};
use super::search::{SearchHit, SearchKind};
use super::subjects::{
    SchemaCompatibility, SchemaReference, SchemaType, SubjectDetail, SubjectRow, SubjectRowsResult,
};
use super::topics::{
    CleanupPolicy, PartitionRow, TopicDetail, TopicGroupRow, TopicRow, TopicRowPage, TopicSortField,
};
use super::updates::{ResyncReason, TopicRate, Update};
use super::whoami::{ClusterGrant, Identity, PrivilegeName};

pub fn typescript() -> String {
    let cfg = ts_rs::Config::from_env();
    let mut out = String::from("// Generated by `cargo xtask types`. Do not edit.\n\n");
    macro_rules! emit {
        ($($ty:ty),+ $(,)?) => {
            $(
                out.push_str("export ");
                out.push_str(&<$ty as TS>::decl(&cfg));
                out.push_str("\n\n");
            )+
        };
    }
    emit!(
        Int64,
        PrivilegeName,
        ClusterGrant,
        Identity,
        LaneHealth,
        ClusterHealth,
        CleanupPolicy,
        TopicRow,
        TopicRowPage,
        PartitionRow,
        TopicDetail,
        GroupState,
        MemberAssignment,
        GroupMember,
        GroupOffset,
        GroupRow,
        GroupRowPage,
        GroupDetail,
        TopicGroupRow,
        BrokerRow,
        ConfigSource,
        ConfigEntry,
        SchemaType,
        SchemaCompatibility,
        SubjectRow,
        SubjectRowsResult,
        SchemaReference,
        SubjectDetail,
        AclAuthorizer,
        AclResourceType,
        AclPatternType,
        AclOperation,
        AclPermission,
        Acl,
        AclListing,
        Compression,
        RecordOrder,
        RecordHeader,
        Record,
        RecordPage,
        SearchKind,
        SearchHit,
        TopicSortField,
        TopicRate,
        ResyncReason,
        Update,
    );
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_typescript_is_checked_in() {
        let path =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("web/src/api/types.gen.ts");
        let actual = std::fs::read_to_string(&path).unwrap_or_default();

        assert_eq!(
            actual,
            typescript(),
            "frontend types are stale; run `cargo xtask types`"
        );
    }
}
